/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', {
  "get": {
    "/status/sse": {
      "pikkuFuncName": "progressiveEnhancementExample",
      "route": "/status/sse",
      "method": "get"
    },
    "/status/http": {
      "pikkuFuncName": "progressiveEnhancementExample",
      "route": "/status/http",
      "method": "get"
    }
  },
  "post": {},
  "put": {},
  "delete": {},
  "head": {},
  "patch": {},
  "options": {}
})